# Generated by Django 2.2.5 on 2019-10-05 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20191005_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='grade',
        ),
        migrations.AddField(
            model_name='student',
            name='grade_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='App.Grade'),
            preserve_default=False,
        ),
    ]
